const bodyparts1 = {
	"CT_Angiography": [
		'',
		'Abdomen',
		'Abdomen Aorta & Lower Extremities',
		'CHEST - Non-coronary',
		'Head',
		'Neck',
		'Pelvis'
	],


	"CT_Scan": [
		'',
		'3D Reconsturction',
		'Abdomen',
		'Abdomen & Pelvis',
		'Abdomen & Pelvis (Angiogram)',
		'Brain',
		'Cardiac Score/Calcium Screening',
		'Cervical Spine',
		'Chest',
		'Colonography Diagnostic',
		'Colonography Screening',
		'Lower Extremity',
		'Lower Extremity (Angiogram)',
		'Luing Screening',
		'Lumbar Spine',
		'Maxillofacial',
		'Orbital Face, Neck & Skull',
		'Pelvis',
		'Soft Tissue Neck',
		'Thoracic Spine',
		'Upper Extremity',
		'Upper Extremity (Angiogram)'
	],

	"EMG_NCV": [
		'',
		'<4 Muscles Tested',
		'5 or more muscles tested (Complete)',
		'Non-Extrimity'
	],

	"Flouroscopy": [
		'',
		'Barium Enema - COLON',
		'Barium Enema with AIR CONT',
		'Barium Swallow / Esophagus Exam',
		'Barium Swallow / Esophagus Exam (Double Contrast)',
		'Intravenous Urography, or Pyelography W/ or W/o KUB',
		'OCG- Oral Cholecystography',
		'Small Bowel',
		'UGI / Small Bowel Follow Through (Double Contrast)',
		'UGI / Small Bowel Follow Through W/ Air',
		'UGI- Single Contrast W/ KUB',
		'UGI/Small Bowel Follow Through (Single Contrast)',
		'Upper Esophagram',
		'Upper Gastro Intestinal(GI) Tract W/ Air',
		'Upper Gastro Intestinal(GI) Tract W/ KUB',
		'VCUG (Voiding Cystogram)'
	],

	"Mammo": [
		'',
		'3D DIGITAL SCREENING',
		'Mammogram (Diagnostic)',
		'Screening Mammogram (Digital)',
		'Stereotactic Biopsy',
		'Stereotactic Biopsy additional site'
	],

	"MR_Angiography": [
		'',
		'Abdomen',
		'Chest or Thorax',
		'Head and Neck',
		'Lower Extremity',
		'Neck',
		'Pelvis',
		'Upper extremity'
	],

	"MR_Arthrogram": [
		'',
		'Hip, Knee, or Ankle, (Lower Extremity)',
		'Shoulder, Elbow or Wrist(Upper Extremity)',
	],

	"MRI": [
		'',
		'Abdomen',
		'Brain',
		'Brain Spectroscopy',
		'Breast',
		'BREAST (Left or Right) w/o contrast',
		'Breast Localization',
		'Cervical Spine',
		'Chest',
		'Hip, Knee, or Ankle, (Lower Extremity, Joint)',
		'Humerus, Forearm or Hand(Upper Extremity, Non-Joint)',
		'Lumbar Spine',
		'Orbital Face&Neck',
		'Pelvis',
		'Shoulder, Elbow or Wrist(Upper Extremity, Joint)',
		'Thigh, Lower Leg or Foot(Lower Extremity, Non-Joint)',
		'Thoracic Spine',
		'TMJ'
	],

	"Myelograms": [
		'',
		'Cervical',
		'Cervical/Throracic/ Lumbar (Injection)',
		'Lumbrosacral',
		'Thoracic'
	],

	"NonMR_Arthrogram": [
		'',
		'Ankle',
		'Elbow',
		'Hip',
		'Knee',
		'Shoulder'
	],


	"Nuclear_Medicine": [
		'',
		'Bone Scan Limited Views',
		'Bone Scan Multiple Views',
		'Bone Scan Three Phase',
		'Bone Scan Whole Body',
		'Brain Spect (DaTscan)',
		'Gallium Scan',
		'Hepatobilary With Ejection Fraction (HIDA)',
		'Hepatobiliary Scan with Pharm',
		'Kidney Image With Flow & Function, Single W/Pharm',
		'Liver Scan Spect (Hemangioma)',
		'Liver/Spleen Scan Static',
		'Meckels Scan',
		'MUGA First Pass Technique (Murfreesboro Only)',
		'MYOCARDIAL PERFUSION Imaging/Pharmacologic with 93015',
		'Nuclear Exam Parathyroid Scan',
		'Nuclear Exam Parathyroid Scan with Spect',
		'NUCLEAR EXAM THYROID (with UPTAKE) (single or muliple quantitative measurements)',
		'Octreo Scan',
		'Renal Scan w. Mag 3',
		'Rest MUGA Gated Cardiac (Murfreesboro Only)',
		'Thyroid Imaging With Uptake, Multi-Determ Single or Multiple'
	],

	"PET": [
		'',
		'Brain Imag',
		'Scan with CT full body',
		'Scan with CT Limited',
		'Scan with CT Skull to mid thigh'
	],

	"Special_Procedures": [
		'',
		'Angioplasty Femoral/Popliteal',
		'Atherectomy Stent',
		'Cervical or Thoracic ESI w/ imaging',
		'Cervical or Thoracic ESI w/o imaging',
		'Cervical/Thoracic Discography',
		'Cervical/Thoracic Facet Block',
		'Cervical/Thoracic Nerve Block',
		'Extremity Venogram Bilateral',
		'Extremity Venogram Unilateral',
		'Lumbar Discography',
		'Lumbar ESI w/ imaging',
		'Lumbar ESI w/o imaging',
		'Lumbar Facet Block',
		'Lumbar Kyphoplasty',
		'Lumbar Nerve Block, Lumbar or Sacral',
		'Lumbar Puncture w/ Imaging',
		'Lumbar Vertebroplasty',
		'Thoracic Kyphoplasty',
		'Thoracic Vertebroplasty',
		'Trigger Point Injection (one or two Muscles)',
		'Trigger Point Injection (three or more Muscles)',
		'Vein Ablation (First Vein Treatment)',
		'Vein Ablation (Second Vein Treatment)'
	],

	"Ultrasound": [
		'',
		'Abdominal Complete',
		'Abdominal Limited',
		'Aorta, AAA Screening',
		'Aorta, IVC, Iliac; Duplex, Limited or Unilateral',
		'Aorta, IVC, Iliac; Duplex. Complete Bilateral',
		'Arterial ABI (Ankle Brachial/Arm Brachial)',
		'Arterial Duplex Doppler Lower Extremity Complete',
		'Arterial Duplex Doppler Lower Extremity Limited',
		'Arterial Duplex Doppler Upper Extremity Complete',
		'Arterial Duplex Doppler Upper Extremity Limited',
		'Arterial Physiologic Bilateral (Extremity)',
		'Arterial, Mesenteric, Visceral Duplex',
		'Breast (Unilateral)',
		'Breast Biopsy',
		'Breast Biopsy - each additional lesion',
		'BREAST FNA/FINE NEEDLE ASPIRATION - additional lesions',
		'BREAST FNA/FINE NEEDLE ASPIRATION including Ultrasound Guidance - First lesion',
		'Breast Limited Diagnostics Exam',
		'Cardiovascular Stress Test (Murfreesboro Only)',
		'Carotids- Doppler Duplex Complete',
		'Carotids- Doppler Duplex Limited',
		'Doppler Lower Extremity Venous',
		'Doppler, Abdominal/Pelvic',
		'Echocardiogram- 2D',
		'Elastography',
		'Extremity Non-Vascular Complete',
		'Extremity Non-Vascular Limited',
		'Fibroscan',
		'OB - 1st Trimester Transvaginal',
		'OB 1st Trimester (additional fetus)',
		'OB first Trimester',
		'OB Ultrasound (greater than 14 weeks)',
		'Pelvic Non-Obstetric Complete',
		'Pelvic Non-Obstetric Limited or Follow-up',
		'Pelvic Transvaginal Non-Obstetric',
		'Retroperitoneal Duplex Complete',
		'Retroperitoneal, Limited',
		'Scrotum / Tetiscular',
		'Soft Tissue Head',
		'Soft Tissue Neck',
		'Soft Tissue Thyroid/Parathyroid',
		'Transplanted Kidney',
		'Venous Duplex Doppler- Extremity Complete'
	],

	"XRay": [
		'',
		'Abadomen(1 View)',
		'Abadomen(2 Views)',
		'Acomioclavicular Joints',
		'Angkle left & right (2 VIEWS)',
		'Angkle left & right (3 VIEWS)',
		'Bone Density (DEXA) Scan',
		'Bone Evaluation Infant',
		'Bone Length Study',
		'Bone Survey Adult Complete',
		'Boneage',
		'Cervical Spine (<4 Views)',
		'Cervical Spine (4 or 5 Views)',
		'Chest (1 View)',
		'Chest (2 Views)',
		'Chest with Apical Lordo',
		'Chest with Oblique Projec',
		'Clavicle (2 Views)',
		'Coccyx / Sacrum (2 Views)',
		'DEXA (hips, pelvis, spine) with FRAX (all patients 40-90)',
		'Elbow left /right',
		'Exam of Abdomen KUB with Oblique',
		'Exam of Knee left or Right - ANIKA (4 Views)',
		'Exam OF Mandible (4 views)',
		'Facial Bones (3 Views)',
		'Femur left /right (2 Views)',
		'Fingers left /right (2 Views)',
		'Foot left /right (2 Views)',
		'Foot left /right (3 Views - Complete)',
		'Forearm left /right (2 Views)',
		'Hand left /right (2 Views)',
		'Hand left /right (3 Views)',
		'Heel/Calcaneus left /right (2 Views)',
		'Hip left /right W/ or W/o Pelvis(2-3 Views)',
		'Hip left /right W/ or W/o Pelvis(4 Views)',
		'Hip With Pelvis (1 View)',
		'Hips with Pelvis (2 views)',
		'Hips with Pelvis (3 - 4 views)',
		'Hips with Pelvis (5 or more views)',
		'Humerus left /right (2 views)',
		'Knee left /right Bilateral (2 views)',
		'Knee left /right Bilateral (3 views)',
		'Lumbar Spine (<4 views)',
		'Lumbar Spine (4 views)',
		'Lumbar Spine (6 views)',
		'Mastoids',
		'Nasal Bones (3 or more views)',
		'Neck Soft Tissue',
		'Orbital Xray',
		'Orbital Xray (Minimum 4 Views)',
		'Pelvis (1-2 views)',
		'Ribs',
		'Ribs left /right (3 views)',
		'Ribs left /right Incl Chest (4 views)',
		'Sacroiliac Joints left /right (3 views)',
		'Scapula, Complete',
		'Shoulder L/R/Bilateral (3 views)',
		'Single Film to R/O FB',
		'Sinuses (<3 views)',
		'Sinuses (3 or more views)',
		'Skull (4 views)',
		'Smith and Nephew / Visionaire (Lower ext)',
		'Spine Cerv Incl Obli Flex and Ext (6 Views)',
		'Spine Entire Survey / Scoliosis Study',
		'Sterno Clavi joint (3 views)',
		'Sternum (2 views)',
		'Thoracic Spine (2 Views)',
		'Tibia/Fibula left /right',
		'TMJ',
		'Toe(s) left /right (2 views)',
		'Wrist left /right (2 views)',
		'Wrist left /right Min (3 views)'
	],
};

