const cptcodes = {
"MR_AngiographyHead and NeckW/o ContrastNA": "70544",
"MR_AngiographyHead and NeckW/ ContrastNA": "70545",
"MR_AngiographyHead and NeckW/ & W/o ContrastNA": "70546",
"MR_AngiographyLower ExtremityW/ or W/o ContrastNA": "73725",
"UltrasoundDoppler Lower Extremity VenousNAUnilateral": "93971",
"UltrasoundScrotum / TetiscularNANA": "76870",
"UltrasoundSoft Tissue HeadNANA": "76536",
"FlouroscopyBarium Swallow / Esophagus ExamW/ ContrastNA": "74220",
"FlouroscopyBarium Enema - COLONW/ or W/o ContrastNA": "74270",
"FlouroscopyBarium Enema with AIR CONTNANA": "74280",
"FlouroscopyIntravenous Urography, or Pyelography W/ or W/o KUBNANA": "74400",
"FlouroscopySmall BowelNANA": "74250",
"FlouroscopyUpper Gastro Intestinal(GI) Tract W/ KUBNANA": "74247",
"FlouroscopyUGI / Small Bowel Follow Through (Double Contrast)NANA": "74249",
"FlouroscopyUGI- Single Contrast W/ KUBNANA": "74241",
"FlouroscopyUGI/Small Bowel Follow Through (Single Contrast)NANA": "74245",
"MammoMammogram (Diagnostic)NABilateral": "77066",
"MammoScreening Mammogram (Digital)NANA": "77067",
"MammoMammogram (Diagnostic)NAUnilateral": "77065",
"XRayBone Density (DEXA) ScanNANA": "77080",
"Nuclear_MedicineBone Scan Three PhaseNANA": "78315",
"Nuclear_MedicineBone Scan Whole BodyNANA": "78306",
"Nuclear_MedicineHepatobilary With Ejection Fraction (HIDA)W/ or W/o ContrastNA": "78226",
"Nuclear_MedicineKidney Image With Flow & Function, Single W/PharmNANA": "78708",
"Nuclear_MedicineRest MUGA Gated Cardiac (Murfreesboro Only)NANA": "78472",
"Nuclear_MedicineThyroid Imaging With Uptake, Multi-Determ Single or MultipleNANA": "78012",
"XRayBone Length StudyNANA": "77073",
"FlouroscopyUGI / Small Bowel Follow Through W/ AirNANA": "74249",
"FlouroscopyUpper Gastro Intestinal(GI) Tract W/ AirNANA": "74247",
"Mammo3D DIGITAL SCREENINGNANA": "77063",
"UltrasoundBREAST FNA/FINE NEEDLE ASPIRATION including Ultrasound Guidance - First lesionNANA": "10005",
"UltrasoundBREAST FNA/FINE NEEDLE ASPIRATION - additional lesionsNANA": "10006",
"UltrasoundSoft Tissue NeckNANA": "76536",
"UltrasoundSoft Tissue Thyroid/ParathyroidNANA": "76536",
"Nuclear_MedicineMYOCARDIAL PERFUSION Imaging/Pharmacologic with 93015NANA": "78452",
"CT_ScanOrbital Face, Neck & SkullW/o ContrastNA": "70480",
"CT_ScanOrbital Face, Neck & SkullW/ ContrastNA": "70481",
"CT_ScanOrbital Face, Neck & SkullW/ & W/o ContrastNA": "70482",
"CT_ScanMaxillofacialW/o ContrastNA": "70486",
"CT_ScanMaxillofacialW/ ContrastNA": "70487",
"CT_ScanMaxillofacialW/ & W/o ContrastNA": "70488",
"CT_ScanSoft Tissue NeckW/o ContrastNA": "70490",
"CT_ScanSoft Tissue NeckW/ ContrastNA": "70491",
"CT_ScanSoft Tissue NeckW/ & W/o ContrastNA": "70492",
"CT_ScanUpper ExtremityW/o ContrastNA": "73200",
"CT_ScanUpper ExtremityW/ ContrastNA": "73201",
"CT_ScanUpper ExtremityW/ & W/o ContrastNA": "73202",
"CT_ScanLower ExtremityW/o ContrastNA": "73700",
"CT_ScanLower ExtremityW/ ContrastNA": "73701",
"CT_ScanLower ExtremityW/ & W/o ContrastNA": "73702",
"CT_ScanBrainW/o ContrastNA": "70450",
"CT_ScanBrainW/ ContrastNA": "70460",
"CT_ScanBrainW/ & W/o ContrastNA": "70470",
"CT_ScanCervical SpineW/o ContrastNA": "72125",
"CT_ScanCervical SpineW/ ContrastNA": "72126",
"CT_ScanCervical SpineW/ & W/o ContrastNA": "72127",
"CT_ScanChestW/o ContrastNA": "71250",
"CT_ScanChestW/ ContrastNA": "71260",
"CT_ScanChestW/ & W/o ContrastNA": "71270",
"CT_ScanThoracic SpineW/o ContrastNA": "72128",
"CT_ScanThoracic SpineW/ ContrastNA": "72129",
"CT_ScanThoracic SpineW/ & W/o ContrastNA": "72130",
"CT_ScanAbdomen & PelvisW/o ContrastNA": "74176",
"CT_ScanAbdomen & PelvisW/ ContrastNA": "74177",
"CT_ScanAbdomen & PelvisW/ & W/o ContrastNA": "74178",
"CT_ScanLumbar SpineW/o ContrastNA": "72131",
"CT_ScanLumbar SpineW/ ContrastNA": "72132",
"CT_ScanLumbar SpineW/ & W/o ContrastNA": "72133",
"MRIOrbital Face&NeckW/o ContrastNA": "70540",
"MRIOrbital Face&NeckW/ & W/o ContrastNA": "70543",
"MRITMJNANA": "70336",
"MRIShoulder, Elbow or Wrist(Upper Extremity, Joint)W/o ContrastNA": "73221",
"MRIShoulder, Elbow or Wrist(Upper Extremity, Joint)W/ ContrastNA": "73222",
"MRIShoulder, Elbow or Wrist(Upper Extremity, Joint)W/ & W/o ContrastNA": "73223",
"MRIHumerus, Forearm or Hand(Upper Extremity, Non-Joint)W/o ContrastNA": "73218",
"MRIHumerus, Forearm or Hand(Upper Extremity, Non-Joint)W/ & W/o ContrastNA": "73220",
"MRIHip, Knee, or Ankle, (Lower Extremity, Joint)W/o ContrastNA": "73721",
"MRIHip, Knee, or Ankle, (Lower Extremity, Joint)W/ ContrastNA": "73722",
"MRIHip, Knee, or Ankle, (Lower Extremity, Joint)W/ & W/o ContrastNA": "73723",
"MRIThigh, Lower Leg or Foot(Lower Extremity, Non-Joint)W/o ContrastNA": "73718",
"MRIThigh, Lower Leg or Foot(Lower Extremity, Non-Joint)W/ & W/o ContrastNA": "73720",
"MRIBrainW/o ContrastNA": "70551",
"MRIBrainW/ & W/o ContrastNA": "70553",
"MRICervical SpineW/o ContrastNA": "72141",
"MRICervical SpineW/ & W/o ContrastNA": "72156",
"MRIChestW/o ContrastNA": "71550",
"MRIChestW/ & W/o ContrastNA": "71552",
"MRIBreastW/ & W/o ContrastNA": "77059",
"MRIThoracic SpineW/o ContrastNA": "72146",
"MRIThoracic SpineW/ & W/o ContrastNA": "72157",
"MRIAbdomenW/o ContrastNA": "74181",
"MRIAbdomenW/ & W/o ContrastNA": "74183",
"MRILumbar SpineW/o ContrastNA": "72148",
"MRILumbar SpineW/ & W/o ContrastNA": "72158",
"MRIPelvisW/o ContrastNA": "72195",
"MRIPelvisW/ & W/o ContrastNA": "72197",
"MRIAbdomenW/ ContrastNA": "74182",
"MRIBRAINW/ ContrastNA": "70552",
"MRIBreastW/o ContrastBilateral": "77047",
"MRIBreastW/ & W/o ContrastUnilateral": "77048",
"MRIBreastW/ & W/o ContrastBilateral": "77049",
"MRICervical SpineW/ ContrastNA": "72142",
"MRIThigh, Lower Leg or Foot(Lower Extremity, Non-Joint)W/ ContrastNA": "73719",
"MRILumbar SpineW/ ContrastNA": "72149",
"MRIOrbital Face&NeckW/ ContrastNA": "70542",
"MRIPelvisW/ ContrastNA": "72196",
"MRIThoracic SpineW/ ContrastNA": "72147",
"MRIHumerus, Forearm or Hand(Upper Extremity, Non-Joint)W/ ContrastNA": "73219",
"MR_AngiographyAbdomenW/ or W/o ContrastNA": "74185",
"MR_AngiographyChest or ThoraxW/ or W/o ContrastNA": "71555",
"MR_AngiographyNeckW/o ContrastNA": "70547",
"MR_AngiographyNeckW/ ContrastNA": "70548",
"MR_AngiographyNeckW/ & W/o ContrastNA": "70549",
"MR_AngiographyPelvisW/ or W/o ContrastNA": "72198",
"MR_AngiographyUpper extremityW/ or W/o ContrastNA": "73225",
"MR_ArthrogramHip, Knee, or Ankle, (Lower Extremity)NANA": "77002, 73722, 23350, Q9967, A9575",
"MR_ArthrogramShoulder, Elbow or Wrist(Upper Extremity)NANA": "77002, 73222, 23350, Q9967, A9575",
"NonMR_ArthrogramAnkleNANA": "73615",
"NonMR_ArthrogramElbowNANA": "73085",
"NonMR_ArthrogramHipNANA": "73525",
"NonMR_ArthrogramKneeNANA": "73580",
"NonMR_ArthrogramShoulderNANA": "73040",
"MyelogramsCervicalNANA": "72240",
"MyelogramsCervical/Throracic/ Lumbar (Injection)NANA": "62284",
"MyelogramsThoracicNANA": "72255",
"MyelogramsLumbrosacralNANA": "72265",
"CT_ScanAbdomenW/o ContrastNA": "74150",
"CT_ScanAbdomenW/ ContrastNA": "74160",
"CT_ScanAbdomenW/ & W/o ContrastNA": "74170",
"CT_ScanCardiac Score/Calcium ScreeningNANA": "75571",
"CT_AngiographyCHEST - Non-coronaryW/ and /or W/o contrastNA": "71275",
"CT_ScanPelvisW/ & W/o ContrastNA": "72194",
"CT_ScanPevisW/ ContrastNA": "72193",
"CT_ScanPevisW/o ContrastNA": "72192",
"CT_Scan3D ReconsturctionNANA": "76376/7",
"CT AngiographyAbdomenW/ or W/o ContrastNA": "74175",
"CT_AngiographyAbdomen Aorta & Lower ExtremitiesW/ or W/o ContrastNA": "75635",
"CT_AngiographyHeadW/ and /or W/o contrastNA": "70496",
"CT_AngiographyNeckW/ and /or W/o contrastNA": "70498",
"CT_AngiographyPelvisW/ & W/o ContrastNA": "72191",
"Special_ProceduresThoracic VertebroplastyNANA": "22510",
"Special_ProceduresLumbar VertebroplastyNANA": "22511",
"Special_ProceduresThoracic KyphoplastyNANA": "22512",
"Special_ProceduresLumbar KyphoplastyNANA": "22514",
"Special_ProceduresCervical or Thoracic ESI w/o imagingNANA": "62320",
"Special_ProceduresCervical or Thoracic ESI w/ imagingNANA": "62321",
"Special_ProceduresLumbar ESI w/o imagingNANA": "62322",
"Special_ProceduresLumbar Puncture w/ ImagingNANA": "62270",
"Special_ProceduresCervical/Thoracic DiscographyNANA": "62291",
"Special_ProceduresLumbar DiscographyNANA": "62290",
"Special_ProceduresCervical/Thoracic Nerve BlockNANA": "64479",
"Special_ProceduresLumbar Nerve Block, Lumbar or SacralNANA": "64483",
"Special_ProceduresCervical/Thoracic Facet BlockNANA": "64490",
"Special_ProceduresLumbar Facet BlockNANA": "64493",
"Special_ProceduresTrigger Point Injection (one or two Muscles)NANA": "20552",
"Special_ProceduresTrigger Point Injection (three or more Muscles)NANA": "20553",
"Special_ProceduresAngioplasty Femoral/PoplitealNANA": "37224",
"Special_ProceduresAtherectomy StentNANA": "37227",
"Special_ProceduresExtremity Venogram UnilateralNANA": "75820",
"Special_ProceduresExtremity Venogram BilateralNANA": "75822",
"Special_ProceduresVein Ablation (First Vein Treatment)NANA": "36478",
"Special_ProceduresVein Ablation (Second Vein Treatment)NANA": "36479",
"UltrasoundAbdominal CompleteNANA": "76700",
"UltrasoundAbdominal LimitedNANA": "76705",
"UltrasoundAorta, IVC, Iliac; Duplex. Complete BilateralNANA": "93978",
"UltrasoundArterial, Mesenteric, Visceral DuplexNANA": "93976",
"UltrasoundArterial ABI (Ankle Brachial/Arm Brachial)NANA": "93922",
"UltrasoundArterial Physiologic Bilateral (Extremity)NANA": "93923",
"UltrasoundArterial Duplex Doppler Lower Extremity CompleteNANA": "93925",
"UltrasoundArterial Duplex Doppler Lower Extremity LimitedNANA": "93926",
"UltrasoundArterial Duplex Doppler Upper Extremity CompleteNANA": "93930",
"UltrasoundArterial Duplex Doppler Upper Extremity LimitedNANA": "93931",
"UltrasoundAorta, IVC, Iliac; Duplex, Limited or UnilateralNANA": "93979",
"UltrasoundBreast (Unilateral)NANA": "76641",
"UltrasoundCarotids- Doppler Duplex CompleteNANA": "93880",
"UltrasoundCarotids- Doppler Duplex LimitedNANA": "93882",
"UltrasoundCardiovascular Stress Test (Murfreesboro Only)NANA": "93015",
"UltrasoundEchocardiogram- 2DNANA": "93306",
"UltrasoundExtremity Non-Vascular CompleteNANA": "76881",
"UltrasoundExtremity Non-Vascular LimitedNANA": "76882",
"UltrasoundPelvic Non-Obstetric CompleteNANA": "76856",
"UltrasoundPelvic Non-Obstetric Limited or Follow-upNANA": "76857",
"UltrasoundPelvic Transvaginal Non-ObstetricNANA": "76830",
"UltrasoundOB first TrimesterNANA": "76801",
"UltrasoundOB Ultrasound (greater than 14 weeks)NANA": "76805",
"UltrasoundVenous Duplex Doppler- Extremity CompleteNANA": "93970",
"UltrasoundRetroperitoneal Duplex CompleteNANA": "76770",
"UltrasoundRetroperitoneal, LimitedNANA": "76775",
"FlouroscopyBarium Swallow / Esophagus Exam (Double Contrast)NANA": "74230",
"FlouroscopyOCG- Oral CholecystographyNANA": "74290",
"FlouroscopyVCUG (Voiding Cystogram)NANA": "74455",
"Nuclear_MedicineBone Scan Limited ViewsNANA": "78300",
"Nuclear_MedicineBone Scan Multiple ViewsNANA": "78305",
"Nuclear_MedicineMUGA First Pass Technique (Murfreesboro Only)NANA": "78468",
"CT_ScanAbdomen & Pelvis (Angiogram)W/ & W/o ContrastNA": "74174",
"CT_ScanLower Extremity (Angiogram)W/ and /or W/o contrastNA": "73706",
"CT_ScanUpper Extremity (Angiogram)W/ and /or W/o contrastNA": "73206",
"CT_ScanColonography DiagnosticNANA": "74261",
"CT_ScanColonography ScreeningNANA": "74263",
"CT_ScanLuing ScreeningW/o ContrastNA": "G0297",
"FlouroscopyUpper EsophagramNANA": "74210",
"MammoStereotactic BiopsyNANA": "19081",
"MammoStereotactic Biopsy additional siteNANA": "19082",
"MRIBrain SpectroscopyNANA": "76390",
"MRIBREAST (Left or Right) w/o contrastW/o ContrastNA": "77046",
"MRIBreast LocalizationNANA": "77021",
"MRIChestW/ contrastNA": "71551",
"PETBrain ImagNANA": "78608",
"PETScan with CT LimitedNANA": "78814",
"PETScan with CT Skull to mid thighNANA": "78815",
"PETScan with CT full bodyNANA": "78816",
"UltrasoundFibroscanNANA": "91200",
"UltrasoundAorta, AAA ScreeningNANA": "76706",
"UltrasoundBreast BiopsyNANA": "19083",
"UltrasoundBreast Biopsy - each additional lesionNANA": "19084",
"UltrasoundBreast Limited Diagnostics ExamNANA": "76642",
"UltrasoundDoppler, Abdominal/PelvicNANA": "93975",
"UltrasoundElastographyNANA": "76981",
"UltrasoundOB - 1st Trimester TransvaginalNANA": "76817",
"UltrasoundOB 1st Trimester (additional fetus)NANA": "76812",
"UltrasoundTransplanted KidneyNANA": "76776",
"Nuclear_MedicineBrain Spect (DaTscan)NANA": "78607",
"Nuclear_MedicineNUCLEAR EXAM THYROID (with UPTAKE) (single or muliple quantitative measurements)NANA": "78014",
"Nuclear_MedicineNuclear Exam Parathyroid ScanNANA": "78070",
"Nuclear_MedicineNuclear Exam Parathyroid Scan with SpectNANA": "78071",
"Nuclear_MedicineGallium ScanNANA": "78800",
"Nuclear_MedicineHepatobiliary Scan with PharmNANA": "78227",
"Nuclear_MedicineLiver Scan Spect (Hemangioma)NANA": "78206",
"Nuclear_MedicineLiver/Spleen Scan StaticNANA": "78215",
"Nuclear_MedicineMeckels ScanNANA": "78290",
"Nuclear_MedicineOctreo ScanNANA": "78804",
"Nuclear_MedicineRenal Scan w. Mag 3NANA": "78707",
"XRayAbadomen(1 View)NANA": "74018",
"XRayAbadomen(2 Views)NANA": "74019",
"XRayAcomioclavicular JointsNANA": "73050",
"XRayAngkle left & right (2 VIEWS)NABilateral": "73600",
"XRayAngkle left & right (3 VIEWS)NABilateral": "73610",
"XRayBoneageNANA": "77072",
"XRayBone Evaluation InfantNANA": "77076",
"XRayBone Survey Adult CompleteNANA": "77075",
"XRayCervical Spine (<4 Views)NANA": "72040",
"XRayCervical Spine (4 or 5 Views)NANA": "72050",
"XRayChest (1 View)NANA": "71045",
"XRayChest (2 Views)NANA": "71046",
"XRayChest with Apical LordoNANA": "71047",
"XRayChest with Oblique ProjecNANA": "71048",
"XRayClavicle (2 Views)NANA": "73000",
"XRayCoccyx / Sacrum (2 Views)NANA": "72220",
"XRayDEXA (hips, pelvis, spine) with FRAX (all patients 40-90)NANA": "77085",
"XRayElbow left /rightNANA": "73070",
"XRayEye for Foreign BodyNANA": "70030",
"XRayExam of Abdomen KUB with ObliqueNANA": "74021",
"XRayExam of Knee left or Right - ANIKA (4 Views)NABilateral": "73564",
"XRayExam OF Mandible (4 views)NANA": "70110",
"XRayFacial Bones (3 Views)NANA": "70150",
"XRayFemur left /right (2 Views)NABilateral": "73552",
"XRayFingers left /right (2 Views)NABilateral": "73140",
"XRayForearm left /right (2 Views)NANA": "73090",
"XRayFoot left /right (2 Views)NANA": "73620",
"XRayFoot left /right (3 Views - Complete)NABilateral": "73630",
"XRayHand left /right (2 Views)NANA": "73120",
"XRayHand left /right (3 Views)NABilateral": "73130",
"XRayHeel/Calcaneus left /right (2 Views)NABilateral": "73650",
"XRayHip With Pelvis (1 View)NAUnilateral": "73501",
"XRayHip left /right W/ or W/o Pelvis(2-3 Views)NANA": "73502",
"XRayHip left /right W/ or W/o Pelvis(4 Views)NANA": "73503",
"XRayHips with Pelvis (2 views)NABilateral": "73521",
"XRayHips with Pelvis (3 - 4 views)NABilateral": "73522",
"XRayHips with Pelvis (5 or more views)NABilateral": "73523",
"XRayHumerus left /right (2 views)NANA": "73060",
"XRayKnee left /right Bilateral (2 views)NANA": "73560",
"XRayKnee left /right Bilateral (3 views)NANA": "73562",
"XRayLumbar Spine (<4 views)NANA": "72100",
"XRayLumbar Spine (4 views)NANA": "72110",
"XRayLumbar Spine (6 views)NANA": "72114",
"XRayMastoidsNANA": "70130",
"XRayNasal Bones (3 or more views)NANA": "70160",
"XRayNeck Soft TissueNANA": "70360",
"XRayOrbitsNANA": "70200",
"XRayPelvis (1-2 views)NANA": "72170",
"XRayRibs left /right (3 views)NABilateral": "71100",
"XRayRibs left /right Incl Chest (4 views)NABilateral": "71101",
"XRayRibsNABilateral": "71110",
"XRaySacroiliac Joints left /right (3 views)NANA": "72200",
"XRaySacroiliac Joints left /right (3 views)NABilateral": "72202",
"XRaySinuses (<3 views)NANA": "70210",
"XRaySinuses (3 or more views)NANA": "70220",
"XRaySkull (4 views)NANA": "70260",
"XRaySpine Cerv Incl Obli Flex and Ext (6 Views)NANA": "72052",
"XRaySpine Entire Survey / Scoliosis StudyNANA": "72082",
"XRaySternum (2 views)NANA": "71120",
"XRaySterno Clavi joint (3 views)NANA": "71130",
"XRayThoracic Spine (2 Views)NANA": "72070",
"XRayScapula, CompleteNANA": "73010",
"XRayShoulder L/R/Bilateral (3 views)NANA": "73030",
"XRaySingle Film to R/O FBNANA": "76010",
"XRaySmith and Nephew / Visionaire (Lower ext)NANA": "77077",
"XRayTibia/Fibula left /rightNABilateral": "73590",
"XRayTMJNANA": "70330",
"XRayToe(s) left /right (2 views)NANA": "73660",
"XRayWrist left /right (2 views)NANA": "73100",
"XRayWrist left /right Min (3 views)NANA": "73110",
"Special_ProceduresLumbar ESI w/ imagingNANA": "62323",
"EMG_NCV<4 Muscles TestedNANA": "95885",
"EMG_NCV5 or more muscles tested (Complete)NANA": "95886",
"EMG_NCVNon-ExtrimityNANA": "95887"

}

