const notestext = {
"MR_AngiographyHead and NeckW/o ContrastNA": "0",
"MR_AngiographyHead and NeckW/ ContrastNA": "1",
"MR_AngiographyHead and NeckW/ & W/o ContrastNA": "1",
"MR_AngiographyLower ExtremityW/ or W/o ContrastNA": "1",
"UltrasoundDoppler Lower Extremity VenousNAUnilateral": "0",
"UltrasoundScrotum / TetiscularNANA": "0",
"UltrasoundSoft Tissue HeadNANA": "0",
"FlouroscopyBarium Swallow / Esophagus ExamW/ ContrastNA": "1",
"FlouroscopyBarium Enema - COLONW/ or W/o ContrastNA": "1",
"FlouroscopyBarium Enema with AIR CONTNANA": "0",
"FlouroscopyIntravenous Urography, or Pyelography W/ or W/o KUBNANA": "0",
"FlouroscopySmall BowelNANA": "0",
"FlouroscopyUpper Gastro Intestinal(GI) Tract W/ KUBNANA": "0",
"FlouroscopyUGI / Small Bowel Follow Through (Double Contrast)NANA": "0",
"FlouroscopyUGI- Single Contrast W/ KUBNANA": "0",
"FlouroscopyUGI/Small Bowel Follow Through (Single Contrast)NANA": "0",
"MammoMammogram (Diagnostic)NABilateral": "3",
"MammoScreening Mammogram (Digital)NANA": "0",
"MammoMammogram (Diagnostic)NAUnilateral": "0",
"XRayBone Density (DEXA) ScanNANA": "0",
"Nuclear_MedicineBone Scan Three PhaseNANA": "0",
"Nuclear_MedicineBone Scan Whole BodyNANA": "0",
"Nuclear_MedicineHepatobilary With Ejection Fraction (HIDA)W/ or W/o ContrastNA": "1",
"Nuclear_MedicineKidney Image With Flow & Function, Single W/PharmNANA": "0",
"Nuclear_MedicineRest MUGA Gated Cardiac (Murfreesboro Only)NANA": "0",
"Nuclear_MedicineThyroid Imaging With Uptake, Multi-Determ Single or MultipleNANA": "0",
"XRayBone Length StudyNANA": "0",
"FlouroscopyUGI / Small Bowel Follow Through W/ AirNANA": "0",
"FlouroscopyUpper Gastro Intestinal(GI) Tract W/ AirNANA": "0",
"Mammo3D DIGITAL SCREENINGNANA": "0",
"UltrasoundBREAST FNA/FINE NEEDLE ASPIRATION including Ultrasound Guidance - First lesionNANA": "0",
"UltrasoundBREAST FNA/FINE NEEDLE ASPIRATION - additional lesionsNANA": "0",
"UltrasoundSoft Tissue NeckNANA": "0",
"UltrasoundSoft Tissue Thyroid/ParathyroidNANA": "0",
"Nuclear_MedicineMYOCARDIAL PERFUSION Imaging/Pharmacologic with 93015NANA": "0",
"CT_ScanOrbital Face, Neck & SkullW/o ContrastNA": "0",
"CT_ScanOrbital Face, Neck & SkullW/ ContrastNA": "1",
"CT_ScanOrbital Face, Neck & SkullW/ & W/o ContrastNA": "1",
"CT_ScanMaxillofacialW/o ContrastNA": "0",
"CT_ScanMaxillofacialW/ ContrastNA": "1",
"CT_ScanMaxillofacialW/ & W/o ContrastNA": "1",
"CT_ScanSoft Tissue NeckW/o ContrastNA": "0",
"CT_ScanSoft Tissue NeckW/ ContrastNA": "1",
"CT_ScanSoft Tissue NeckW/ & W/o ContrastNA": "1",
"CT_ScanUpper ExtremityW/o ContrastNA": "0",
"CT_ScanUpper ExtremityW/ ContrastNA": "1",
"CT_ScanUpper ExtremityW/ & W/o ContrastNA": "1",
"CT_ScanLower ExtremityW/o ContrastNA": "0",
"CT_ScanLower ExtremityW/ ContrastNA": "1",
"CT_ScanLower ExtremityW/ & W/o ContrastNA": "1",
"CT_ScanBrainW/o ContrastNA": "0",
"CT_ScanBrainW/ ContrastNA": "1",
"CT_ScanBrainW/ & W/o ContrastNA": "1",
"CT_ScanCervical SpineW/o ContrastNA": "0",
"CT_ScanCervical SpineW/ ContrastNA": "1",
"CT_ScanCervical SpineW/ & W/o ContrastNA": "1",
"CT_ScanChestW/o ContrastNA": "0",
"CT_ScanChestW/ ContrastNA": "1",
"CT_ScanChestW/ & W/o ContrastNA": "1",
"CT_ScanThoracic SpineW/o ContrastNA": "0",
"CT_ScanThoracic SpineW/ ContrastNA": "1",
"CT_ScanThoracic SpineW/ & W/o ContrastNA": "1",
"CT_ScanAbdomen & PelvisW/o ContrastNA": "0",
"CT_ScanAbdomen & PelvisW/ ContrastNA": "1",
"CT_ScanAbdomen & PelvisW/ & W/o ContrastNA": "1",
"CT_ScanLumbar SpineW/o ContrastNA": "0",
"CT_ScanLumbar SpineW/ ContrastNA": "1",
"CT_ScanLumbar SpineW/ & W/o ContrastNA": "1",
"MRIOrbital Face&NeckW/o ContrastNA": "0",
"MRIOrbital Face&NeckW/ & W/o ContrastNA": "1",
"MRITMJNANA": "0",
"MRIShoulder, Elbow or Wrist(Upper Extremity, Joint)W/o ContrastNA": "0",
"MRIShoulder, Elbow or Wrist(Upper Extremity, Joint)W/ ContrastNA": "1",
"MRIShoulder, Elbow or Wrist(Upper Extremity, Joint)W/ & W/o ContrastNA": "1",
"MRIHumerus, Forearm or Hand(Upper Extremity, Non-Joint)W/o ContrastNA": "0",
"MRIHumerus, Forearm or Hand(Upper Extremity, Non-Joint)W/ & W/o ContrastNA": "1",
"MRIHip, Knee, or Ankle, (Lower Extremity, Joint)W/o ContrastNA": "0",
"MRIHip, Knee, or Ankle, (Lower Extremity, Joint)W/ ContrastNA": "1",
"MRIHip, Knee, or Ankle, (Lower Extremity, Joint)W/ & W/o ContrastNA": "1",
"MRIThigh, Lower Leg or Foot(Lower Extremity, Non-Joint)W/o ContrastNA": "0",
"MRIThigh, Lower Leg or Foot(Lower Extremity, Non-Joint)W/ & W/o ContrastNA": "1",
"MRIBrainW/o ContrastNA": "0",
"MRIBrainW/ & W/o ContrastNA": "1",
"MRICervical SpineW/o ContrastNA": "0",
"MRICervical SpineW/ & W/o ContrastNA": "1",
"MRIChestW/o ContrastNA": "0",
"MRIChestW/ & W/o ContrastNA": "1",
"MRIBreastW/ & W/o ContrastNA": "1",
"MRIThoracic SpineW/o ContrastNA": "0",
"MRIThoracic SpineW/ & W/o ContrastNA": "1",
"MRIAbdomenW/o ContrastNA": "0",
"MRIAbdomenW/ & W/o ContrastNA": "1",
"MRILumbar SpineW/o ContrastNA": "0",
"MRILumbar SpineW/ & W/o ContrastNA": "1",
"MRIPelvisW/o ContrastNA": "0",
"MRIPelvisW/ & W/o ContrastNA": "1",
"MRIAbdomenW/ ContrastNA": "1",
"MRIBRAINW/ ContrastNA": "1",
"MRIBreastW/o ContrastBilateral": "3",
"MRIBreastW/ & W/o ContrastUnilateral": "1",
"MRIBreastW/ & W/o ContrastBilateral": "1",
"MRICervical SpineW/ ContrastNA": "1",
"MRIThigh, Lower Leg or Foot(Lower Extremity, Non-Joint)W/ ContrastNA": "1",
"MRILumbar SpineW/ ContrastNA": "1",
"MRIOrbital Face&NeckW/ ContrastNA": "1",
"MRIPelvisW/ ContrastNA": "1",
"MRIThoracic SpineW/ ContrastNA": "1",
"MRIHumerus, Forearm or Hand(Upper Extremity, Non-Joint)W/ ContrastNA": "1",
"MR_AngiographyAbdomenW/ or W/o ContrastNA": "1",
"MR_AngiographyChest or ThoraxW/ or W/o ContrastNA": "1",
"MR_AngiographyNeckW/o ContrastNA": "0",
"MR_AngiographyNeckW/ ContrastNA": "1",
"MR_AngiographyNeckW/ & W/o ContrastNA": "1",
"MR_AngiographyPelvisW/ or W/o ContrastNA": "1",
"MR_AngiographyUpper extremityW/ or W/o ContrastNA": "1",
"MR_ArthrogramHip, Knee, or Ankle, (Lower Extremity)NANA": "0",
"MR_ArthrogramShoulder, Elbow or Wrist(Upper Extremity)NANA": "0",
"NonMR_ArthrogramAnkleNANA": "0",
"NonMR_ArthrogramElbowNANA": "0",
"NonMR_ArthrogramHipNANA": "0",
"NonMR_ArthrogramKneeNANA": "0",
"NonMR_ArthrogramShoulderNANA": "0",
"MyelogramsCervicalNANA": "0",
"MyelogramsCervical/Throracic/ Lumbar (Injection)NANA": "0",
"MyelogramsThoracicNANA": "0",
"MyelogramsLumbrosacralNANA": "0",
"CT_ScanAbdomenW/o ContrastNA": "0",
"CT_ScanAbdomenW/ ContrastNA": "1",
"CT_ScanAbdomenW/ & W/o ContrastNA": "1",
"CT_ScanCardiac Score/Calcium ScreeningNANA": "0",
"CT_AngiographyCHEST - Non-coronaryW/ and /or W/o contrastNA": "1",
"CT_ScanPelvisW/ & W/o ContrastNA": "1",
"CT_ScanPevisW/ ContrastNA": "1",
"CT_ScanPevisW/o ContrastNA": "0",
"CT_Scan3D ReconsturctionNANA": "0",
"CT AngiographyAbdomenW/ or W/o ContrastNA": "1",
"CT_AngiographyAbdomen Aorta & Lower ExtremitiesW/ or W/o ContrastNA": "1",
"CT_AngiographyHeadW/ and /or W/o contrastNA": "1",
"CT_AngiographyNeckW/ and /or W/o contrastNA": "1",
"CT_AngiographyPelvisW/ & W/o ContrastNA": "1",
"Special_ProceduresThoracic VertebroplastyNANA": "0",
"Special_ProceduresLumbar VertebroplastyNANA": "0",
"Special_ProceduresThoracic KyphoplastyNANA": "0",
"Special_ProceduresLumbar KyphoplastyNANA": "0",
"Special_ProceduresCervical or Thoracic ESI w/o imagingNANA": "0",
"Special_ProceduresCervical or Thoracic ESI w/ imagingNANA": "0",
"Special_ProceduresLumbar ESI w/o imagingNANA": "0",
"Special_ProceduresLumbar Puncture w/ ImagingNANA": "0",
"Special_ProceduresCervical/Thoracic DiscographyNANA": "0",
"Special_ProceduresLumbar DiscographyNANA": "0",
"Special_ProceduresCervical/Thoracic Nerve BlockNANA": "0",
"Special_ProceduresLumbar Nerve Block, Lumbar or SacralNANA": "0",
"Special_ProceduresCervical/Thoracic Facet BlockNANA": "0",
"Special_ProceduresLumbar Facet BlockNANA": "0",
"Special_ProceduresTrigger Point Injection (one or two Muscles)NANA": "0",
"Special_ProceduresTrigger Point Injection (three or more Muscles)NANA": "0",
"Special_ProceduresAngioplasty Femoral/PoplitealNANA": "0",
"Special_ProceduresAtherectomy StentNANA": "0",
"Special_ProceduresExtremity Venogram UnilateralNANA": "0",
"Special_ProceduresExtremity Venogram BilateralNANA": "0",
"Special_ProceduresVein Ablation (First Vein Treatment)NANA": "0",
"Special_ProceduresVein Ablation (Second Vein Treatment)NANA": "0",
"UltrasoundAbdominal CompleteNANA": "0",
"UltrasoundAbdominal LimitedNANA": "0",
"UltrasoundAorta, IVC, Iliac; Duplex. Complete BilateralNANA": "0",
"UltrasoundArterial, Mesenteric, Visceral DuplexNANA": "0",
"UltrasoundArterial ABI (Ankle Brachial/Arm Brachial)NANA": "0",
"UltrasoundArterial Physiologic Bilateral (Extremity)NANA": "0",
"UltrasoundArterial Duplex Doppler Lower Extremity CompleteNANA": "0",
"UltrasoundArterial Duplex Doppler Lower Extremity LimitedNANA": "0",
"UltrasoundArterial Duplex Doppler Upper Extremity CompleteNANA": "0",
"UltrasoundArterial Duplex Doppler Upper Extremity LimitedNANA": "0",
"UltrasoundAorta, IVC, Iliac; Duplex, Limited or UnilateralNANA": "0",
"UltrasoundBreast (Unilateral)NANA": "0",
"UltrasoundCarotids- Doppler Duplex CompleteNANA": "0",
"UltrasoundCarotids- Doppler Duplex LimitedNANA": "0",
"UltrasoundCardiovascular Stress Test (Murfreesboro Only)NANA": "0",
"UltrasoundEchocardiogram- 2DNANA": "0",
"UltrasoundExtremity Non-Vascular CompleteNANA": "0",
"UltrasoundExtremity Non-Vascular LimitedNANA": "0",
"UltrasoundPelvic Non-Obstetric CompleteNANA": "0",
"UltrasoundPelvic Non-Obstetric Limited or Follow-upNANA": "0",
"UltrasoundPelvic Transvaginal Non-ObstetricNANA": "0",
"UltrasoundOB first TrimesterNANA": "0",
"UltrasoundOB Ultrasound (greater than 14 weeks)NANA": "0",
"UltrasoundVenous Duplex Doppler- Extremity CompleteNANA": "0",
"UltrasoundRetroperitoneal Duplex CompleteNANA": "0",
"UltrasoundRetroperitoneal, LimitedNANA": "0",
"FlouroscopyBarium Swallow / Esophagus Exam (Double Contrast)NANA": "0",
"FlouroscopyOCG- Oral CholecystographyNANA": "0",
"FlouroscopyVCUG (Voiding Cystogram)NANA": "0",
"Nuclear_MedicineBone Scan Limited ViewsNANA": "0",
"Nuclear_MedicineBone Scan Multiple ViewsNANA": "0",
"Nuclear_MedicineMUGA First Pass Technique (Murfreesboro Only)NANA": "0",
"CT_ScanAbdomen & Pelvis (Angiogram)W/ & W/o ContrastNA": "1",
"CT_ScanLower Extremity (Angiogram)W/ and /or W/o contrastNA": "1",
"CT_ScanUpper Extremity (Angiogram)W/ and /or W/o contrastNA": "1",
"CT_ScanColonography DiagnosticNANA": "0",
"CT_ScanColonography ScreeningNANA": "0",
"CT_ScanLuing ScreeningW/o ContrastNA": "0",
"FlouroscopyUpper EsophagramNANA": "0",
"MammoStereotactic BiopsyNANA": "0",
"MammoStereotactic Biopsy additional siteNANA": "0",
"MRIBrain SpectroscopyNANA": "0",
"MRIBREAST (Left or Right) w/o contrastW/o ContrastNA": "0",
"MRIBreast LocalizationNANA": "0",
"MRIChestW/ contrastNA": "1",
"PETBrain ImagNANA": "0",
"PETScan with CT LimitedNANA": "0",
"PETScan with CT Skull to mid thighNANA": "0",
"PETScan with CT full bodyNANA": "0",
"UltrasoundFibroscanNANA": "0",
"UltrasoundAorta, AAA ScreeningNANA": "0",
"UltrasoundBreast BiopsyNANA": "0",
"UltrasoundBreast Biopsy - each additional lesionNANA": "0",
"UltrasoundBreast Limited Diagnostics ExamNANA": "0",
"UltrasoundDoppler, Abdominal/PelvicNANA": "0",
"UltrasoundElastographyNANA": "0",
"UltrasoundOB - 1st Trimester TransvaginalNANA": "0",
"UltrasoundOB 1st Trimester (additional fetus)NANA": "0",
"UltrasoundTransplanted KidneyNANA": "0",
"Nuclear_MedicineBrain Spect (DaTscan)NANA": "0",
"Nuclear_MedicineNUCLEAR EXAM THYROID (with UPTAKE) (single or muliple quantitative measurements)NANA": "0",
"Nuclear_MedicineNuclear Exam Parathyroid ScanNANA": "0",
"Nuclear_MedicineNuclear Exam Parathyroid Scan with SpectNANA": "0",
"Nuclear_MedicineGallium ScanNANA": "0",
"Nuclear_MedicineHepatobiliary Scan with PharmNANA": "0",
"Nuclear_MedicineLiver Scan Spect (Hemangioma)NANA": "0",
"Nuclear_MedicineLiver/Spleen Scan StaticNANA": "0",
"Nuclear_MedicineMeckels ScanNANA": "0",
"Nuclear_MedicineOctreo ScanNANA": "0",
"Nuclear_MedicineRenal Scan w. Mag 3NANA": "0",
"XRayAbadomen(1 View)NANA": "0",
"XRayAbadomen(2 Views)NANA": "0",
"XRayAcomioclavicular JointsNANA": "0",
"XRayAngkle left & right (2 VIEWS)NABilateral": "3",
"XRayAngkle left & right (3 VIEWS)NABilateral": "3",
"XRayBoneageNANA": "0",
"XRayBone Evaluation InfantNANA": "0",
"XRayBone Survey Adult CompleteNANA": "0",
"XRayCervical Spine (<4 Views)NANA": "0",
"XRayCervical Spine (4 or 5 Views)NANA": "0",
"XRayChest (1 View)NANA": "0",
"XRayChest (2 Views)NANA": "0",
"XRayChest with Apical LordoNANA": "0",
"XRayChest with Oblique ProjecNANA": "0",
"XRayClavicle (2 Views)NANA": "0",
"XRayCoccyx / Sacrum (2 Views)NANA": "0",
"XRayDEXA (hips, pelvis, spine) with FRAX (all patients 40-90)NANA": "0",
"XRayElbow left /rightNANA": "0",
"XRayEye for Foreign BodyNANA": "0",
"XRayExam of Abdomen KUB with ObliqueNANA": "0",
"XRayExam of Knee left or Right - ANIKA (4 Views)NABilateral": "3",
"XRayExam OF Mandible (4 views)NANA": "0",
"XRayFacial Bones (3 Views)NANA": "0",
"XRayFemur left /right (2 Views)NABilateral": "3",
"XRayFingers left /right (2 Views)NABilateral": "3",
"XRayForearm left /right (2 Views)NANA": "0",
"XRayFoot left /right (2 Views)NANA": "0",
"XRayFoot left /right (3 Views - Complete)NABilateral": "3",
"XRayHand left /right (2 Views)NANA": "0",
"XRayHand left /right (3 Views)NABilateral": "3",
"XRayHeel/Calcaneus left /right (2 Views)NABilateral": "3",
"XRayHip With Pelvis (1 View)NAUnilateral": "0",
"XRayHip left /right W/ or W/o Pelvis(2-3 Views)NANA": "0",
"XRayHip left /right W/ or W/o Pelvis(4 Views)NANA": "0",
"XRayHips with Pelvis (2 views)NABilateral": "3",
"XRayHips with Pelvis (3 - 4 views)NABilateral": "3",
"XRayHips with Pelvis (5 or more views)NABilateral": "3",
"XRayHumerus left /right (2 views)NANA": "0",
"XRayKnee left /right Bilateral (2 views)NANA": "0",
"XRayKnee left /right Bilateral (3 views)NANA": "0",
"XRayLumbar Spine (<4 views)NANA": "0",
"XRayLumbar Spine (4 views)NANA": "0",
"XRayLumbar Spine (6 views)NANA": "0",
"XRayMastoidsNANA": "0",
"XRayNasal Bones (3 or more views)NANA": "0",
"XRayNeck Soft TissueNANA": "0",
"XRayOrbitsNANA": "0",
"XRayPelvis (1-2 views)NANA": "0",
"XRayRibs left /right (3 views)NABilateral": "3",
"XRayRibs left /right Incl Chest (4 views)NABilateral": "3",
"XRayRibsNABilateral": "3",
"XRaySacroiliac Joints left /right (3 views)NANA": "0",
"XRaySacroiliac Joints left /right (3 views)NABilateral": "3",
"XRaySinuses (<3 views)NANA": "0",
"XRaySinuses (3 or more views)NANA": "0",
"XRaySkull (4 views)NANA": "0",
"XRaySpine Cerv Incl Obli Flex and Ext (6 Views)NANA": "0",
"XRaySpine Entire Survey / Scoliosis StudyNANA": "0",
"XRaySternum (2 views)NANA": "0",
"XRaySterno Clavi joint (3 views)NANA": "0",
"XRayThoracic Spine (2 Views)NANA": "0",
"XRayScapula, CompleteNANA": "0",
"XRayShoulder L/R/Bilateral (3 views)NANA": "0",
"XRaySingle Film to R/O FBNANA": "0",
"XRaySmith and Nephew / Visionaire (Lower ext)NANA": "0",
"XRayTibia/Fibula left /rightNABilateral": "3",
"XRayTMJNANA": "0",
"XRayToe(s) left /right (2 views)NANA": "0",
"XRayWrist left /right (2 views)NANA": "0",
"XRayWrist left /right Min (3 views)NANA": "0",
"Special_ProceduresLumbar ESI w/ imagingNANA": "0",
"EMG_NCV<4 Muscles TestedNANA": "2",
"EMG_NCV5 or more muscles tested (Complete)NANA": "2",
"EMG_NCVNon-ExtrimityNANA": "2",

}