const notestext = {
"MR_AngiographyHead and NeckW/o ContrastNA": "0",
"MR_AngiographyHead and NeckW/ ContrastNA": "1",
"MR_AngiographyHead and NeckW/ & W/o ContrastNA": "1",
"MR_AngiographyLower ExtremityW/ or W/o ContrastNA": "1",
"UltrasoundDoppler Lower Extremity VenousNAUnilateral": "0",
"UltrasoundScrotum / TetiscularNANA": "0",
"UltrasoundSoft Tissue HeadNANA": "0",
"FlouroscopyBarium Swallow / Esophagus ExamW/ ContrastNA": "1",
"FlouroscopyBarium Enema - COLONW/ or W/o ContrastNA": "1",
"FlouroscopyBarium Enema with AIR CONTNANA": "0",
"FlouroscopyIntravenous Urography, or Pyelography W/ or W/o KUBNANA": "0",
"FlouroscopySmall BowelNANA": "0",
"FlouroscopyUpper Gastro Intestinal(GI) Tract W/ KUBNANA": "0",
"FlouroscopyUGI / Small Bowel Follow Through (Double Contrast)NANA": "0",
"FlouroscopyUGI- Single Contrast W/ KUBNANA": "0",
"FlouroscopyUGI/Small Bowel Follow Through (Single Contrast)NANA": "0",
"MammoMammogram (Diagnostic)NABilateral": "3",
"MammoScreening Mammogram (Digital)NANA": "0",
"MammoMammogram (Diagnostic)NAUnilateral": "0",
"XRayBone Density (DEXA) ScanNANA": "0",
"Nuclear_MedicineBone Scan Three PhaseNANA": "0",
"Nuclear_MedicineBone Scan Whole BodyNANA": "0",
"Nuclear_MedicineHepatobilary With Ejection Fraction (HIDA)W/ or W/o ContrastNA": "1",
"Nuclear_MedicineKidney Image With Flow & Function, Single W/PharmNANA": "0",
"Nuclear_MedicineRest MUGA Gated Cardiac (Murfreesboro Only)NANA": "0",
"Nuclear_MedicineThyroid Imaging With Uptake, Multi-Determ Single or MultipleNANA": "0",
"XRayBone Length StudyNANA": "0",
"FlouroscopyUGI / Small Bowel Follow Through W/ AirNANA": "0",
"FlouroscopyUpper Gastro Intestinal(GI) Tract W/ AirNANA": "0",
"Mammo3D DIGITAL SCREENINGNANA": "0",
"UltrasoundBREAST FNA/FINE NEEDLE ASPIRATION including Ultrasound Guidance - First lesionNANA": "0",
"UltrasoundBREAST FNA/FINE NEEDLE ASPIRATION - additional lesionsNANA": "0",
"UltrasoundSoft Tissue NeckNANA": "0",
"UltrasoundSoft Tissue Thyroid/ParathyroidNANA": "0",
"Nuclear_MedicineMYOCARDIAL PERFUSION Imaging/Pharmacologic with 93015NANA": "0",
"CT_ScanOrbital Face, Neck & SkullW/o ContrastNA": "0",
"CT_ScanOrbital Face, Neck & SkullW/ ContrastNA": "1",
"CT_ScanOrbital Face, Neck & SkullW/ & W/o ContrastNA": "1",
"CT_ScanMaxillofacialW/o ContrastNA": "0",
"CT_ScanMaxillofacialW/ ContrastNA": "1",
"CT_ScanMaxillofacialW/ & W/o ContrastNA": "1",
"CT_ScanSoft Tissue NeckW/o ContrastNA": "0",
"CT_ScanSoft Tissue NeckW/ ContrastNA": "1",
"CT_ScanSoft Tissue NeckW/ & W/o ContrastNA": "1",
"CT_ScanUpper ExtremityW/o ContrastNA": "0",
"CT_ScanUpper ExtremityW/ ContrastNA": "1",
"CT_ScanUpper ExtremityW/ & W/o ContrastNA": "1",
"CT_ScanLower ExtremityW/o ContrastNA": "0",
"CT_ScanLower ExtremityW/ ContrastNA": "1",
"CT_ScanLower ExtremityW/ & W/o ContrastNA": "1",
"CT_ScanBrainW/o ContrastNA": "0",
"CT_ScanBrainW/ ContrastNA": "1",
"CT_ScanBrainW/ & W/o ContrastNA": "1",
"CT_ScanCervical SpineW/o ContrastNA": "0",
"CT_ScanCervical SpineW/ ContrastNA": "1",
"CT_ScanCervical SpineW/ & W/o ContrastNA": "1",
"CT_ScanChestW/o ContrastNA": "0",
"CT_ScanChestW/ ContrastNA": "1",
"CT_ScanChestW/ & W/o ContrastNA": "1",
"CT_ScanThoracic SpineW/o ContrastNA": "0",
"CT_ScanThoracic SpineW/ ContrastNA": "1",
"CT_ScanThoracic SpineW/ & W/o ContrastNA": "1",
"CT_ScanAbdomen & PelvisW/o ContrastNA": "0",
"CT_ScanAbdomen & PelvisW/ ContrastNA": "1",
"CT_ScanAbdomen & PelvisW/ & W/o ContrastNA": "1",
"CT_ScanLumbar SpineW/o ContrastNA": "0",
"CT_ScanLumbar SpineW/ ContrastNA": "1",
"CT_ScanLumbar SpineW/ & W/o ContrastNA": "1",
"MRIOrbital Face&NeckW/o ContrastNA": "0",
"MRIOrbital Face&NeckW/ & W/o ContrastNA": "1",
"MRITMJNANA": "0",
"MRIShoulder, Elbow or Wrist(Upper Extremity, Joint)W/o ContrastNA": "0",
"MRIShoulder, Elbow or Wrist(Upper Extremity, Joint)W/ ContrastNA": "1",
"MRIShoulder, Elbow or Wrist(Upper Extremity, Joint)W/ & W/o ContrastNA": "1",
"MRIHumerus, Forearm or Hand(Upper Extremity, Non-Joint)W/o ContrastNA": "0",
"MRIHumerus, Forearm or Hand(Upper Extremity, Non-Joint)W/ & W/o ContrastNA": "1",
"MRIHip, Knee, or Ankle, (Lower Extremity, Joint)W/o ContrastNA": "0",
"MRIHip, Knee, or Ankle, (Lower Extremity, Joint)W/ ContrastNA": "1",
"MRIHip, Knee, or Ankle, (Lower Extremity, Joint)W/ & W/o ContrastNA": "1",
"MRIThigh, Lower Leg or Foot(Lower Extremity, Non-Joint)W/o ContrastNA": "0",
"MRIThigh, Lower Leg or Foot(Lower Extremity, Non-Joint)W/ & W/o ContrastNA": "1",
"MRIBrainW/o ContrastNA": "0",
"MRIBrainW/ & W/o ContrastNA": "1",
"MRICervical SpineW/o ContrastNA": "0",
"MRICervical SpineW/ & W/o ContrastNA": "1",
"MRIChestW/o ContrastNA": "0",
"MRIChestW/ & W/o ContrastNA": "1",
"MRIBreastW/ & W/o ContrastNA": "1",
"MRIThoracic SpineW/o ContrastNA": "0",
"MRIThoracic SpineW/ & W/o ContrastNA": "1",
"MRIAbdomenW/o ContrastNA": "0",
"MRIAbdomenW/ & W/o ContrastNA": "1",
"MRILumbar SpineW/o ContrastNA": "0",
"MRILumbar SpineW/ & W/o ContrastNA": "1",
"MRIPelvisW/o ContrastNA": "0"
  
}