const sides = {
    "MRIBreastW/ & W/o Contrast": "1",
    "MammoMammogram (Diagnostic)NA": "2",
    "XRaySacroiliac Joints left /right (3 views)NA": "3",
    "CT_AngiographyAbdomen Aorta & Lower ExtremitiesW/ or W/o Contrast": "4",
    "CT_AngiographyAbdomenW/ or W/o Contrast": "4",
    "CT_AngiographyCHEST - Non-coronaryW/ and /or W/o contrast": "4",
    "CT_AngiographyHeadW/ and /or W/o contrast": "4",
    "CT_AngiographyNeckW/ and /or W/o contrast": "4",
    "CT_AngiographyPelvisW/ & W/o Contrast": "4",
    "CT_Scan3D ReconsturctionNA": "4",
    "CT_ScanAbdomen & Pelvis (Angiogram)W/ & W/o Contrast": "4",
    "CT_ScanAbdomen & PelvisW/ & W/o Contrast": "4",
    "CT_ScanAbdomen & PelvisW/ Contrast": "4",
    "CT_ScanAbdomen & PelvisW/o Contrast": "4",
    "CT_ScanAbdomenW/ & W/o Contrast": "4",
    "CT_ScanAbdomenW/ Contrast": "4",
    "CT_ScanAbdomenW/o Contrast": "4",
    "CT_ScanBrainW/ & W/o Contrast": "4",
    "CT_ScanBrainW/ Contrast": "4",
    "CT_ScanBrainW/o Contrast": "4",
    "CT_ScanCardiac Score/Calcium ScreeningNA": "4",
    "CT_ScanCervical SpineW/ & W/o Contrast": "4",
    "CT_ScanCervical SpineW/ Contrast": "4",
    "CT_ScanCervical SpineW/o Contrast": "4",
    "CT_ScanChestW/ & W/o Contrast": "4",
    "CT_ScanChestW/ Contrast": "4",
    "CT_ScanChestW/o Contrast": "4",
    "CT_ScanColonography DiagnosticNA": "4",
    "CT_ScanColonography ScreeningNA": "4",
    "CT_ScanLower Extremity (Angiogram)W/ and /or W/o contrast": "4",
    "CT_ScanLower ExtremityW/ & W/o Contrast": "4",
    "CT_ScanLower ExtremityW/ Contrast": "4",
    "CT_ScanLower ExtremityW/o Contrast": "4",
    "CT_ScanLuing ScreeningW/o Contrast": "4",
    "CT_ScanLumbar SpineW/ & W/o Contrast": "4",
    "CT_ScanLumbar SpineW/ Contrast": "4",
    "CT_ScanLumbar SpineW/o Contrast": "4",
    "CT_ScanMaxillofacialW/ & W/o Contrast": "4",
    "CT_ScanMaxillofacialW/ Contrast": "4",
    "CT_ScanMaxillofacialW/o Contrast": "4",
    "CT_ScanOrbital Face, Neck & SkullW/ & W/o Contrast": "4",
    "CT_ScanOrbital Face, Neck & SkullW/ Contrast": "4",
    "CT_ScanOrbital Face, Neck & SkullW/o Contrast": "4",
    "CT_ScanPelvisW/ & W/o Contrast": "4",
    "CT_ScanPevisW/ Contrast": "4",
    "CT_ScanPevisW/o Contrast": "4",
    "CT_ScanSoft Tissue NeckW/ & W/o Contrast": "4",
    "CT_ScanSoft Tissue NeckW/ Contrast": "4",
    "CT_ScanSoft Tissue NeckW/o Contrast": "4",
    "CT_ScanThoracic SpineW/ & W/o Contrast": "4",
    "CT_ScanThoracic SpineW/ Contrast": "4",
    "CT_ScanThoracic SpineW/o Contrast": "4",
    "CT_ScanUpper Extremity (Angiogram)W/ and /or W/o contrast": "4",
    "CT_ScanUpper ExtremityW/ & W/o Contrast": "4",
    "CT_ScanUpper ExtremityW/ Contrast": "4",
    "CT_ScanUpper ExtremityW/o Contrast": "4",
    "EMG_NCV<4 Muscles TestedNA": "4",
    "EMG_NCV5 or more muscles tested (Complete)NA": "4",
    "EMG_NCVNon-ExtrimityNA": "4",
    "FlouroscopyBarium Enema - COLONW/ or W/o Contrast": "4",
    "FlouroscopyBarium Enema with AIR CONTNA": "4",
    "FlouroscopyBarium Swallow / Esophagus Exam (Double Contrast)NA": "4",
    "FlouroscopyBarium Swallow / Esophagus ExamW/ Contrast": "4",
    "FlouroscopyIntravenous Urography, or Pyelography W/ or W/o KUBNA": "4",
    "FlouroscopyOCG- Oral CholecystographyNA": "4",
    "FlouroscopySmall BowelNA": "4",
    "FlouroscopyUGI / Small Bowel Follow Through (Double Contrast)NA": "4",
    "FlouroscopyUGI / Small Bowel Follow Through W/ AirNA": "4",
    "FlouroscopyUGI- Single Contrast W/ KUBNA": "4",
    "FlouroscopyUGI/Small Bowel Follow Through (Single Contrast)NA": "4",
    "FlouroscopyUpper EsophagramNA": "4",
    "FlouroscopyUpper Gastro Intestinal(GI) Tract W/ AirNA": "4",
    "FlouroscopyUpper Gastro Intestinal(GI) Tract W/ KUBNA": "4",
    "FlouroscopyVCUG (Voiding Cystogram)NA": "4",
    "Mammo3D DIGITAL SCREENINGNA": "4",
    "MammoScreening Mammogram (Digital)NA": "4",
    "MammoStereotactic Biopsy additional siteNA": "4",
    "MammoStereotactic BiopsyNA": "4",
    "MR_AngiographyAbdomenW/ or W/o Contrast": "4",
    "MR_AngiographyChest or ThoraxW/ or W/o Contrast": "4",
    "MR_AngiographyHead and NeckW/ & W/o Contrast": "4",
    "MR_AngiographyHead and NeckW/ Contrast": "4",
    "MR_AngiographyHead and NeckW/o Contrast": "4",
    "MR_AngiographyLower ExtremityW/ or W/o Contrast": "4",
    "MR_AngiographyNeckW/ & W/o Contrast": "4",
    "MR_AngiographyNeckW/ Contrast": "4",
    "MR_AngiographyNeckW/o Contrast": "4",
    "MR_AngiographyPelvisW/ or W/o Contrast": "4",
    "MR_AngiographyUpper extremityW/ or W/o Contrast": "4",
    "MR_ArthrogramHip, Knee, or Ankle, (Lower Extremity)NA": "4",
    "MR_ArthrogramShoulder, Elbow or Wrist(Upper Extremity)NA": "4",
    "MRIAbdomenW/ & W/o Contrast": "4",
    "MRIAbdomenW/ Contrast": "4",
    "MRIAbdomenW/o Contrast": "4",
    "MRIBrain SpectroscopyNA": "4",
    "MRIBrainW/ & W/o Contrast": "4",
    "MRIBRAINW/ Contrast": "4",
    "MRIBrainW/o Contrast": "4",
    "MRIBREAST (Left or Right) w/o contrastW/o Contrast": "4",
    "MRIBreast LocalizationNA": "4",
    "MRIBreastW/o Contrast": "5",
    "MRICervical SpineW/ & W/o Contrast": "4",
    "MRICervical SpineW/ Contrast": "4",
    "MRICervical SpineW/o Contrast": "4",
    "MRIChestW/ & W/o Contrast": "4",
    "MRIChestW/ Contrast": "4",
    "MRIChestW/o Contrast": "4",
    "MRIHip, Knee, or Ankle, (Lower Extremity, Joint)W/ & W/o Contrast": "4",
    "MRIHip, Knee, or Ankle, (Lower Extremity, Joint)W/ Contrast": "4",
    "MRIHip, Knee, or Ankle, (Lower Extremity, Joint)W/o Contrast": "4",
    "MRIHumerus, Forearm or Hand(Upper Extremity, Non-Joint)W/ & W/o Contrast": "4",
    "MRIHumerus, Forearm or Hand(Upper Extremity, Non-Joint)W/ Contrast": "4",
    "MRIHumerus, Forearm or Hand(Upper Extremity, Non-Joint)W/o Contrast": "4",
    "MRILumbar SpineW/ & W/o Contrast": "4",
    "MRILumbar SpineW/ Contrast": "4",
    "MRILumbar SpineW/o Contrast": "4",
    "MRIOrbital Face&NeckW/ & W/o Contrast": "4",
    "MRIOrbital Face&NeckW/ Contrast": "4",
    "MRIOrbital Face&NeckW/o Contrast": "4",
    "MRIPelvisW/ & W/o Contrast": "4",
    "MRIPelvisW/ Contrast": "4",
    "MRIPelvisW/o Contrast": "4",
    "MRIShoulder, Elbow or Wrist(Upper Extremity, Joint)W/ & W/o Contrast": "4",
    "MRIShoulder, Elbow or Wrist(Upper Extremity, Joint)W/ Contrast": "4",
    "MRIShoulder, Elbow or Wrist(Upper Extremity, Joint)W/o Contrast": "4",
    "MRIThigh, Lower Leg or Foot(Lower Extremity, Non-Joint)W/ & W/o Contrast": "4",
    "MRIThigh, Lower Leg or Foot(Lower Extremity, Non-Joint)W/ Contrast": "4",
    "MRIThigh, Lower Leg or Foot(Lower Extremity, Non-Joint)W/o Contrast": "4",
    "MRIThoracic SpineW/ & W/o Contrast": "4",
    "MRIThoracic SpineW/ Contrast": "4",
    "MRIThoracic SpineW/o Contrast": "4",
    "MRITMJNA": "4",
    "MyelogramsCervical/Throracic/ Lumbar (Injection)NA": "4",
    "MyelogramsCervicalNA": "4",
    "MyelogramsLumbrosacralNA": "4",
    "MyelogramsThoracicNA": "4",
    "NonMR_ArthrogramAnkleNA": "4",
    "NonMR_ArthrogramElbowNA": "4",
    "NonMR_ArthrogramHipNA": "4",
    "NonMR_ArthrogramKneeNA": "4",
    "NonMR_ArthrogramShoulderNA": "4",
    "Nuclear_MedicineBone Scan Limited ViewsNA": "4",
    "Nuclear_MedicineBone Scan Multiple ViewsNA": "4",
    "Nuclear_MedicineBone Scan Three PhaseNA": "4",
    "Nuclear_MedicineBone Scan Whole BodyNA": "4",
    "Nuclear_MedicineBrain Spect (DaTscan)NA": "4",
    "Nuclear_MedicineGallium ScanNA": "4",
    "Nuclear_MedicineHepatobilary With Ejection Fraction (HIDA)W/ or W/o Contrast": "4",
    "Nuclear_MedicineHepatobiliary Scan with PharmNA": "4",
    "Nuclear_MedicineKidney Image With Flow & Function, Single W/PharmNA": "4",
    "Nuclear_MedicineLiver Scan Spect (Hemangioma)NA": "4",
    "Nuclear_MedicineLiver/Spleen Scan StaticNA": "4",
    "Nuclear_MedicineMeckels ScanNA": "4",
    "Nuclear_MedicineMUGA First Pass Technique (Murfreesboro Only)NA": "4",
    "Nuclear_MedicineMYOCARDIAL PERFUSION Imaging/Pharmacologic with 93015NA": "4",
    "Nuclear_MedicineNuclear Exam Parathyroid Scan with SpectNA": "4",
    "Nuclear_MedicineNuclear Exam Parathyroid ScanNA": "4",
    "Nuclear_MedicineNUCLEAR EXAM THYROID (with UPTAKE) (single or muliple quantitative measurements)NA": "4",
    "Nuclear_MedicineOctreo ScanNA": "4",
    "Nuclear_MedicineRenal Scan w. Mag 3NA": "4",
    "Nuclear_MedicineRest MUGA Gated Cardiac (Murfreesboro Only)NA": "4",
    "Nuclear_MedicineThyroid Imaging With Uptake, Multi-Determ Single or MultipleNA": "4",
    "PETBrain ImagNA": "4",
    "PETScan with CT full bodyNA": "4",
    "PETScan with CT LimitedNA": "4",
    "PETScan with CT Skull to mid thighNA": "4",
    "Special_ProceduresAngioplasty Femoral/PoplitealNA": "4",
    "Special_ProceduresAtherectomy StentNA": "4",
    "Special_ProceduresCervical or Thoracic ESI w/ imagingNA": "4",
    "Special_ProceduresCervical or Thoracic ESI w/o imagingNA": "4",
    "Special_ProceduresCervical/Thoracic DiscographyNA": "4",
    "Special_ProceduresCervical/Thoracic Facet BlockNA": "4",
    "Special_ProceduresCervical/Thoracic Nerve BlockNA": "4",
    "Special_ProceduresExtremity Venogram BilateralNA": "4",
    "Special_ProceduresExtremity Venogram UnilateralNA": "4",
    "Special_ProceduresLumbar DiscographyNA": "4",
    "Special_ProceduresLumbar ESI w/ imagingNA": "4",
    "Special_ProceduresLumbar ESI w/o imagingNA": "4",
    "Special_ProceduresLumbar Facet BlockNA": "4",
    "Special_ProceduresLumbar KyphoplastyNA": "4",
    "Special_ProceduresLumbar Nerve Block, Lumbar or SacralNA": "4",
    "Special_ProceduresLumbar Puncture w/ ImagingNA": "4",
    "Special_ProceduresLumbar VertebroplastyNA": "4",
    "Special_ProceduresThoracic KyphoplastyNA": "4",
    "Special_ProceduresThoracic VertebroplastyNA": "4",
    "Special_ProceduresTrigger Point Injection (one or two Muscles)NA": "4",
    "Special_ProceduresTrigger Point Injection (three or more Muscles)NA": "4",
    "Special_ProceduresVein Ablation (First Vein Treatment)NA": "4",
    "Special_ProceduresVein Ablation (Second Vein Treatment)NA": "4",
    "UltrasoundAbdominal CompleteNA": "4",
    "UltrasoundAbdominal LimitedNA": "4",
    "UltrasoundAorta, AAA ScreeningNA": "4",
    "UltrasoundAorta, IVC, Iliac; Duplex, Limited or UnilateralNA": "4",
    "UltrasoundAorta, IVC, Iliac; Duplex. Complete BilateralNA": "4",
    "UltrasoundArterial ABI (Ankle Brachial/Arm Brachial)NA": "4",
    "UltrasoundArterial Duplex Doppler Lower Extremity CompleteNA": "4",
    "UltrasoundArterial Duplex Doppler Lower Extremity LimitedNA": "4",
    "UltrasoundArterial Duplex Doppler Upper Extremity CompleteNA": "4",
    "UltrasoundArterial Duplex Doppler Upper Extremity LimitedNA": "4",
    "UltrasoundArterial Physiologic Bilateral (Extremity)NA": "4",
    "UltrasoundArterial, Mesenteric, Visceral DuplexNA": "4",
    "UltrasoundBreast (Unilateral)NA": "4",
    "UltrasoundBreast Biopsy - each additional lesionNA": "4",
    "UltrasoundBreast BiopsyNA": "4",
    "UltrasoundBREAST FNA/FINE NEEDLE ASPIRATION - additional lesionsNA": "4",
    "UltrasoundBREAST FNA/FINE NEEDLE ASPIRATION including Ultrasound Guidance - First lesionNA": "4",
    "UltrasoundBreast Limited Diagnostics ExamNA": "4",
    "UltrasoundCardiovascular Stress Test (Murfreesboro Only)NA": "4",
    "UltrasoundCarotids- Doppler Duplex CompleteNA": "4",
    "UltrasoundCarotids- Doppler Duplex LimitedNA": "4",
    "UltrasoundDoppler Lower Extremity VenousNA": "6",
    "UltrasoundDoppler, Abdominal/PelvicNA": "4",
    "UltrasoundEchocardiogram- 2DNA": "4",
    "UltrasoundElastographyNA": "4",
    "UltrasoundExtremity Non-Vascular CompleteNA": "4",
    "UltrasoundExtremity Non-Vascular LimitedNA": "4",
    "UltrasoundFibroscanNA": "4",
    "UltrasoundOB - 1st Trimester TransvaginalNA": "4",
    "UltrasoundOB 1st Trimester (additional fetus)NA": "4",
    "UltrasoundOB first TrimesterNA": "4",
    "UltrasoundOB Ultrasound (greater than 14 weeks)NA": "4",
    "UltrasoundPelvic Non-Obstetric CompleteNA": "4",
    "UltrasoundPelvic Non-Obstetric Limited or Follow-upNA": "4",
    "UltrasoundPelvic Transvaginal Non-ObstetricNA": "4",
    "UltrasoundRetroperitoneal Duplex CompleteNA": "4",
    "UltrasoundRetroperitoneal, LimitedNA": "4",
    "UltrasoundScrotum / TetiscularNA": "4",
    "UltrasoundSoft Tissue HeadNA": "4",
    "UltrasoundSoft Tissue NeckNA": "4",
    "UltrasoundSoft Tissue Thyroid/ParathyroidNA": "4",
    "UltrasoundTransplanted KidneyNA": "4",
    "UltrasoundVenous Duplex Doppler- Extremity CompleteNA": "4",
    "XRayAbadomen(1 View)NA": "4",
    "XRayAbadomen(2 Views)NA": "4",
    "XRayAcomioclavicular JointsNA": "4",
    "XRayAngkle left & right (2 VIEWS)NA": "5",
    "XRayAngkle left & right (3 VIEWS)NA": "5",
    "XRayBone Density (DEXA) ScanNA": "4",
    "XRayBone Evaluation InfantNA": "4",
    "XRayBone Length StudyNA": "4",
    "XRayBone Survey Adult CompleteNA": "4",
    "XRayBoneageNA": "4",
    "XRayCervical Spine (<4 Views)NA": "4",
    "XRayCervical Spine (4 or 5 Views)NA": "4",
    "XRayChest (1 View)NA": "4",
    "XRayChest (2 Views)NA": "4",
    "XRayChest with Apical LordoNA": "4",
    "XRayChest with Oblique ProjecNA": "4",
    "XRayClavicle (2 Views)NA": "4",
    "XRayCoccyx / Sacrum (2 Views)NA": "4",
    "XRayDEXA (hips, pelvis, spine) with FRAX (all patients 40-90)NA": "4",
    "XRayElbow left /rightNA": "4",
    "XRayExam of Abdomen KUB with ObliqueNA": "4",
    "XRayExam of Knee left or Right - ANIKA (4 Views)NA": "5",
    "XRayExam OF Mandible (4 views)NA": "4",
    "XRayFacial Bones (3 Views)NA": "4",
    "XRayFemur left /right (2 Views)NA": "5",
    "XRayFingers left /right (2 Views)NA": "5",
    "XRayFoot left /right (2 Views)NA": "4",
    "XRayFoot left /right (3 Views - Complete)NA": "5",
    "XRayForearm left /right (2 Views)NA": "4",
    "XRayHand left /right (2 Views)NA": "4",
    "XRayHand left /right (3 Views)NA": "5",
    "XRayHeel/Calcaneus left /right (2 Views)NA": "5",
    "XRayHip left /right W/ or W/o Pelvis(2-3 Views)NA": "4",
    "XRayHip left /right W/ or W/o Pelvis(4 Views)NA": "4",
    "XRayHip With Pelvis (1 View)NA": "6",
    "XRayHips with Pelvis (2 views)NA": "5",
    "XRayHips with Pelvis (3 - 4 views)NA": "5",
    "XRayHips with Pelvis (5 or more views)NA": "5",
    "XRayHumerus left /right (2 views)NA": "4",
    "XRayKnee left /right Bilateral (2 views)NA": "4",
    "XRayKnee left /right Bilateral (3 views)NA": "4",
    "XRayLumbar Spine (<4 views)NA": "4",
    "XRayLumbar Spine (4 views)NA": "4",
    "XRayLumbar Spine (6 views)NA": "4",
    "XRayMastoidsNA": "4",
    "XRayNasal Bones (3 or more views)NA": "4",
    "XRayNeck Soft TissueNA": "4",
    "XRayOrbital Xray (Minimum 4 Views)NA": "4",
    "XRayOrbital XrayNA": "4",
    "XRayPelvis (1-2 views)NA": "4",
    "XRayRibs left /right (3 views)NA": "5",
    "XRayRibs left /right Incl Chest (4 views)NA": "5",
    "XRayRibsNA": "5",
    "XRayScapula, CompleteNA": "4",
    "XRayShoulder L/R/Bilateral (3 views)NA": "4",
    "XRaySingle Film to R/O FBNA": "4",
    "XRaySinuses (<3 views)NA": "4",
    "XRaySinuses (3 or more views)NA": "4",
    "XRaySkull (4 views)NA": "4",
    "XRaySmith and Nephew / Visionaire (Lower ext)NA": "4",
    "XRaySpine Cerv Incl Obli Flex and Ext (6 Views)NA": "4",
    "XRaySpine Entire Survey / Scoliosis StudyNA": "4",
    "XRaySterno Clavi joint (3 views)NA": "4",
    "XRaySternum (2 views)NA": "4",
    "XRayThoracic Spine (2 Views)NA": "4",
    "XRayTibia/Fibula left /rightNA": "5",
    "XRayTMJNA": "4",
    "XRayToe(s) left /right (2 views)NA": "4",
    "XRayWrist left /right (2 views)NA": "4",
    "XRayWrist left /right Min (3 views)NA": "4"

}


